export default  ActionsTypes ={
    LOGIN_INITIATE:'LOGIN_INITIATE',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
   
    SIGNUP_INITIATE :'SIGNUP_INITIATE',
    SIGNUP_FAIL:'SIGNUP_FAIL',
    SIGNUP_SUCCESS:'SIGNUP_SUCCESS',
    
    SIGNIN_INITIATE :'SIGNIN_INITIATE',
    SIGNIN_FAIL:'SIGNIN_FAIL',
    SIGNIN_SUCCESS:'SIGNIN_SUCCESS',

    FILE_UPLOAD_INITIATE :'FILE_UPLOAD_INITIATE',
    FILE_UPLOAD_FAIL:'FILE_UPLOAD_FAIL',
    FILE_UPLOAD_SUCCESS:'FILE_UPLOAD_SUCCESS',
    EMPTY_FILE_UPLOAD_STATE:'EMPTY_FILE_UPLOAD_STATE',
    
    GET_MY_PROFILE_INITIATE:'GET_MY_PROFILE_INITIATE',
    GET_MY_PROFILE_SUCCESS:'GET_MY_PROFILE_SUCCESS',
    GET_MY_PROFILE_FAIL:'GET_MY_PROFILE_FAIL',


    UPDATE_PROFILE_INITIATE:'UPDATE_PROFILE_INITIATE',
    UPDATE_PROFILE_SUCCESS:'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_FAIL:'UPDATE_PROFILE_FAIL',
    EMPTY_PROFILE_STATE:'EMPTY_PROFILE_STATE',
    
    ADD_CATEGORY_INITIATE:'ADD_CATEGORY_INITIATE',
    ADD_CATEGORY_SUCCESS:'ADD_CATEGORY_SUCCESS',
    ADD_CATEGORY_FAIL:'ADD_CATEGORY_FAIL',
    GET_ALL_CATEGORY_INITIATE:'GET_ALL_CATEGORY_INITIATE',
    GET_ALL_CATEGORY_FAIL:'GET_ALL_CATEGORY_FAIL',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',

    GET_ALL_PRODUCTS_INITIATE:'GET_ALL_PRODUCTS_INITIATE',
    GET_ALL_PRODUCTS_FAIL:'GET_ALL_PRODUCTS_FAIL',
    GET_ALL_PRODUCTS_SUCCESS:'GET_ALL_PRODUCTS_SUCCESS',
    EMPTY_PRODUCTS_STATE:'EMPTY_PRODUCTS_STATE',

    UPDATE_CATEGORY_INITIATE:'UPDATE_CATEGORY_INITIATE',
    UPDATE_CATEGORY_SUCCESS:'UPDATE_CATEGORY_SUCCESS',
    UPDATE_CATEGORY_FAIL:'UPDATE_CATEGORY_FAIL',
    EMPTY_CATEGORY_STATE:'EMPTY_ADD_CATEGORY_STATE',

    ADD_SUB_CATEGORY_INITIATE:'ADD_SUB_CATEGORY_INITIATE',
    ADD_SUB_CATEGORY_SUCCESS:'ADD_SUB_CATEGORY_SUCCESS',
    ADD_SUB_CATEGORY_FAIL:'ADD_SUB_CATEGORY_FAIL',
    GET_ALL_SUB_CATEGORY_INITIATE:'GET_ALL_SUB_CATEGORY_INITIATE',
    GET_ALL_SUB_CATEGORY_FAIL:'GET_ALL_SUB_CATEGORY_FAIL',
    GET_ALL_SUB_CATEGORY_SUCCESS:'GET_ALL_SUB_CATEGORY_SUCCESS',
    UPDATE_SUB_CATEGORY_INITIATE:'UPDATE_SUB_CATEGORY_INITIATE',
    UPDATE_SUB_CATEGORY_SUCCESS:'UPDATE_SUB_CATEGORY_SUCCESS',
    UPDATE_SUB_CATEGORY_FAIL:'UPDATE_SUB_CATEGORY_FAIL',
    EMPTY_SUB_CATEGORY_STATE:'EMPTY_ADD_SUB_CATEGORY_STATE',

    ADD_BRAND_INITIATE:'ADD_BRAND_INITIATE',
    ADD_BRAND_SUCCESS:'ADD_BRAND_SUCCESS',
    ADD_BRAND_FAIL:'ADD_BRAND_FAIL',
    GET_ALL_BRAND_INITIATE:'GET_ALL_BRAND_INITIATE',
    GET_ALL_BRAND_FAIL:'GET_ALL_BRAND_FAIL',
    GET_ALL_BRAND_SUCCESS:'GET_ALL_BRAND_SUCCESS',
    UPDATE_BRAND_INITIATE:'UPDATE_BRAND_INITIATE',
    UPDATE_BRAND_SUCCESS:'UPDATE_BRAND_SUCCESS',
    UPDATE_BRAND_FAIL:'UPDATE_BRAND_FAIL',
    EMPTY_BRAND_STATE:'EMPTY_BRAND_STATE',
    
    ADD_MODAL_NUMBER_INITIATE:'ADD_MODAL_NUMBER_INITIATE',
    ADD_MODAL_NUMBER_SUCCESS:'ADD_MODAL_NUMBER_SUCCESS',
    ADD_MODAL_NUMBER_FAIL:'ADD_MODAL_NUMBER_FAIL',
    GET_ALL_MODAL_NUMBER_INITIATE:'GET_ALL_MODAL_NUMBER_INITIATE',
    GET_ALL_MODAL_NUMBER_FAIL:'GET_ALL_MODAL_NUMBER_FAIL',
    GET_ALL_MODAL_NUMBER_SUCCESS:'GET_ALL_MODAL_NUMBER_SUCCESS',
    UPDATE_MODAL_NUMBER_INITIATE:'UPDATE_MODAL_NUMBER_INITIATE',
    UPDATE_MODAL_NUMBER_SUCCESS:'UPDATE_MODAL_NUMBER_SUCCESS',
    UPDATE_MODAL_NUMBER_FAIL:'UPDATE_MODAL_NUMBER_FAIL',
    EMPTY_MODAL_NUMBER_STATE:'EMPTY_MODAL_NUMBER_STATE',


    SHOW_BRAND_MODAL_WINDOW: 'SHOW_BRAND_MODAL_WINDOW',
    HIDE_MODAL_WINDOW: 'HIDE_MODAL_WINDOW',
    EMPTY_HIDE_MODAL_WINDOW_STATE:'EMPTY_HIDE_MODAL_WINDOW_STATE',
    ADD_CATEGORY_SHOW_MODAL_WINDOW:'ADD_CATEGORY_SHOW_MODAL_WINDOW',
    ADD_CATEGORY_HIDE_MODAL_WINDOW:'ADD_CATEGORY_HIDE_MODAL_WINDOW',
    ADD_SUB_CATEGORY_SHOW_MODAL_WINDOW:'ADD_SUB_CATEGORY_SHOW_MODAL_WINDOW',
    SHOW_MODAL_NUMBER_MODAL_WINDOW:'SHOW_MODAL_NUMBER_MODAL_WINDOW',

    GET_TOP_SOLD_PRODUCTS_INITIATE:'GET_TOP_SOLD_PRODUCTS_INITIATE',
    GET_TOP_SOLD_PRODUCTS_FAIL:'GET_TOP_SOLD_PRODUCTS_FAIL',
    GET_TOP_SOLD_PRODUCTS_SUCCESS:'GET_TOP_SOLD_PRODUCTS_SUCCESS',
    EMPTY_TOP_SOLD_PRODUCTS_STATE:'EMPTY_TOP_SOLD_PRODUCTS_STATE',

    GET_ALL_ORDER_BY_USER_ID:'GET_ALL_ORDER_BY_USER_ID',

}